### ISSUE TITLE
mpsse! macro has incorrect enums for enable/disable_adaptive_data_clocking

### ISSUE THREAD

**Issue by quantumdude836** [ftdi-rs/ftdi-mpsse#17]
Attempting to use `mpsse!` with the `enable_adaptive_data_clocking`/`disable_adaptive_data_clocking` commands emits code that tries to reference `MpsseCmd::{EnableDataClocking, DisableDataClocking}`, but these enums don't exist. Instead, they're called `EnableAdaptiveClocking` and `DisableAdaptiveClocking`.

Example code (`ft` is of type `&mut libftd2xx::Ft2232h`):

    {
        mpsse! {
            let cmd = {
                disable_adaptive_data_clocking();
                disable_3phase_data_clocking();
            };
        }
        ft.write_all(&cmd).unwrap();
    }

This results in the following compiler error:

    error[E0599]: no variant or associated item named `DisableDataClocking` found for enum `MpsseCmd` in the current scope
      --> src/main.rs:22:9
       |
    22 | /         mpsse! {
    23 | |             let cmd = {
    24 | |                 disable_adaptive_data_clocking();
    25 | |                 disable_3phase_data_clocking();
    26 | |             };
    27 | |         }
       | |         ^
       | |         |
       | |_________variant or associated item not found in `MpsseCmd`
       |           help: there is a variant with a similar name: `Disable3PhaseClocking`
       |
       = note: this error originates in the macro `mpsse` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by newAM** [comment]
Thanks for the bug report, sorry for the slow response!

Fixed in 0.1.2
